### ISSUE TITLE
Always output .mif file

### ISSUE THREAD

**Issue by emthrm** [kuis-isle3hw/simple_simulator#17]
`-d` オプションを有効にしていない場合でも `.mif` ファイルが生成されてしまう．
https://github.com/kuis-isle3hw/simple_simulator/blob/268cc9d09c95f26fa689ad0343128060690c6eb6/src/Main.java#L24
`mifOutput` の初期値が `true` であるために発生すると考えられる．

**Comment by takasehideki** [comment]
#19 で対応しました．あざまっした！
