### ISSUE TITLE
ShiftLeftRotate miscalculates

### ISSUE THREAD

**Issue by emthrm** [kuis-isle3hw/simple_simulator#18]
[CMP_MOV_SLL_SLR_SRL_SRA_BE_BLT_BLE_BNE](https://github.com/kuis-isle3hw/simple_sample/blob/7db25e67a9cea9753fed0e0e89bfbcf3e62625a0/InstructionTest/4-CMP_MOV_SLL_SLR_SRL_SRA_BE_BLT_BLE_BNE/CMP_MOV_SLL_SLR_SRL_SRA_BE_BLT_BLE_BNE.txt) のシミュレーションにてデバッグモードをオンにすると
17番地に書き込まれた命令の実行前後において
```
[-32768, -1, 0, 0, 0, 0, 0, 0],(1000)
   17 : SLR 0,2
[0, -1, 0, 0, 0, 0, 0, 0],(0100)
```
と出力された．
https://github.com/kuis-isle3hw/simple_simulator/blob/268cc9d09c95f26fa689ad0343128060690c6eb6/src/Operation.java#L412
が意図した通りに動作していないと考えられる．
`int result = com.getRegister(rd)<<d | Operation.cut(com.getRegister(rd), 16 - d, d);` とした場合
```
[-32768, -1, 0, 0, 0, 0, 0, 0],(1000)
   17 : SLR 0,2
[2, -1, 0, 0, 0, 0, 0, 0],(0000)
```
と出力された．

**Comment by NASU41** [comment]
> https://github.com/kuis-isle3hw/simple_simulator/blob/268cc9d09c95f26fa689ad0343128060690c6eb6/src/Operation.java#L4-L7

第2引数は右端のindexなので確かに `16-d` が正しいですね...
修正しますのでしばらくお待ちください
