### ISSUE TITLE
入力命令のビット幅チェックについて

### ISSUE THREAD

**Issue by ken551** [kuis-isle3hw/simple_simulator#8]
（そこまでプログラム側で気を使ってやる必要があるかはわかりませんが）シミュレータに食わせてやる命令.txtで、入力値が所定のビット幅を超えてしまう場合でもエラーを吐かずにそのまま進んでしまうようです

例えば、`LD 9 1(1)`とかの場合、ra=9は3ビットのレジスタアドレスなのですが3ビットの範囲である7を超える9が入力され、結果して出力されるバイナリのビット幅が多くなってたりレジスタ読み出しの時に変な挙動をして変なところで止まったりしてしまうっぽいです

レジスタ８要素なのでoutOfBoundsException的なものが出るかなと思ったんですが、Main.javaの以下↓
https://github.com/kuis-isle3hw/simple_simulator/blob/06ddb9651ecaaec56a57b5aade44d97c3041ca95/src/Main.java#L44-L50
でifにかからないためにoutOfBoundsExceptionが無視されていて、結果として見えないまま先に進んでしまってるみたいです

他に問題が出てるかはちょっとわかりませんが・・・突っ込むテキストファイルの値のチェックをした方がいいように思います  
(もし直してもらう余裕なければやります)

**Comment by takasehideki** [comment]
@ken551 確認できておっけーならCloseしてください

**Comment by ken551** [comment]
範囲指定確認したところ大丈夫そうなのでcloseします
